home/urls.py
from django.urls import path
from . import views
from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('upload/', views.upload, name='upload'),
]

school_made_easy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls')),

    path('assignments/', include('assignments.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from localflavor.us.us_states import US_STATES


class AssignmentManager(models.Manager):
    def get_all_assignments(self):
        return self.filter(email_confirmed=True).all()

    def get_latest_assignments(self):
        return self.filter(email_confirmed=True).all().order_by('-timestamp')


class Assignment(models.Model):
    email = models.EmailField(blank=True, null=True)
    state = models.CharField(choices=US_STATES, max_length=75, blank=True, null=True)
    school_name = models.CharField(max_length=75, blank=True, null=True)
    title = models.CharField(max_length=150)
    class_name = models.CharField(max_length=50)
    notes = models.CharField(max_length=2000)
    timestamp = models.DateTimeField(auto_now_add=False)

    email_confirmed = models.BooleanField(default=False)  # whether email is confirmed or not

    objects = AssignmentManager()  # manager for queries

    def __str__(self):
        return str(self.title)


class AssignmentImageManager(models.Manager):
    def get_for_assignment(self, assignment_obj):
        return self.filter(assignment=assignment_obj)


class AssignmentImage(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    image = models.FileField(upload_to='media/uploads/')
    order = models.PositiveIntegerField(default=False)

    objects = AssignmentImageManager()  # manager for queries

    def __str__(self):
        return str(self.assignment)



'''
This model was going to be used for a email confirmation for when someone upload an assignment, but I was having too
many problems with it.
'''
'''
class EmailConfirmation(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    user_email = models.CharField(max_length=250)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.assignment) + ' - ' + str(self.user_email)
'''

home/forms.py
from django import forms
from django.forms import ModelForm
from .models import Assignment, AssignmentImage


class AssignmentForm(ModelForm):
    class Meta:
        model = Assignment
        exclude = ('timestamp',)

    def __init__(self, *args, **kwargs):
        super(AssignmentForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = forms.widgets.TextInput(attrs={'placeholder': 'Email',
                                                                     'class': 'form-control'})
        self.fields['state'].widget.attrs.update({'class': 'form-control'})
        self.fields['school_name'].widget = forms.widgets.TextInput(attrs={'placeholder': 'School Name',
                                                                           'class': 'form-control'})
        self.fields['class_name'].widget = forms.widgets.TextInput(attrs={'placeholder': 'Class Name',
                                                                           'class': 'form-control'})
        self.fields['title'].widget = forms.widgets.TextInput(attrs={'placeholder': 'Assignment Title',
                                                                     'class': 'form-control'})
        self.fields['notes'].widget = forms.widgets.Textarea(attrs={'placeholder': 'Extra Notes',
                                                                    'class': 'form-control'})


class ImageForm(ModelForm):
    class Meta:
        model = AssignmentImage
        fields = ('image',)

    def __init__(self, *args, **kwargs):
        super(ImageForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget = forms.widgets.FileInput(attrs={'class': 'custom-file-input'})
        self.fields['image'].label = None

home/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.forms import modelformset_factory
from .models import Assignment, AssignmentImage
from .forms import AssignmentForm, ImageForm
from django.utils import timezone


class IndexView(View):
    template_name = 'home/index.html'

    def get(self, request, *args, **kwargs):
        latest_assignments = Assignment.objects.get_latest_assignments()[:3]
        context = {
            'latest_assignments': latest_assignments
        }
        return render(request, self.template_name, context)


def upload(request):
    ImageFormSet = modelformset_factory(
                                        AssignmentImage, form=ImageForm,
                                        min_num=1, validate_min=True, extra=4
                                        )
    if request.method == 'POST':
        form = AssignmentForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES, queryset=AssignmentImage.objects.none())

        if form.is_valid and formset.is_valid():
            instance = form.save(commit=False)
            instance.email_confirmed=True
            instance.timestamp = timezone.now()
            instance.save()

            assignment_pk = instance.pk

            for form in formset.cleaned_data:
                try:
                    image = form['image']
                except:
                    image = None
                if image is not None:
                    image = form['image']
                    image_obj = AssignmentImage(assignment=instance, image=image)
                    image_obj.save()
            return redirect('/assignments/view/'+str(assignment_pk)+'/')
    else:
        form = AssignmentForm()
        formset = ImageFormSet(queryset=AssignmentImage.objects.none())

    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, 'home/upload.html', context)

templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}<title>Title</title>{% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
          crossorigin="anonymous">

    <style>
        body {
            padding-bottom: 4rem;
        }
        .row {
            margin-right: 5%;
            margin-left: 5%;
        }
        #spinner {
            position: absolute;
            z-index: 1;
            opacity: 1!important;
            left: 50%;
            top: 50%;
            font-size: 2.5rem;
            color: #007bff;
            animation-name: spin;
            animation-duration: 1000ms;
            animation-iteration-count: infinite;
            animation-timing-function: linear;
        }
        /* spinner animation */
        @-moz-keyframes spin {
        from { -moz-transform: rotate(0deg); }
        to { -moz-transform: rotate(360deg); }
        }
        @-webkit-keyframes spin {
            from { -webkit-transform: rotate(0deg); }
            to { -webkit-transform: rotate(360deg); }
        }
        @keyframes spin {
            from {transform:rotate(0deg);}
            to {transform:rotate(360deg);}
        }

        @media only screen and (max-width: 580px) {
            .row {
                margin-right: 2.5%;
                margin-left: 2.5%;
            }
            #upload-icon,
            #search-icon {
                font-size: 10rem!important;
            }
        }

    </style>
    {% block head %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">School Made Easy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
            </ul>
            <a href="/assignments/search/" class="btn btn-outline-primary my-2 my-sm-0">Search</a>
        </div>
    </nav>

    <!-- spinner icon -->
    <i id="spinner" class="fas fa-spinner"></i>

    {% block body %}
    {% endblock %}
    {% block script %}
    {% endblock %}
    <script>
        $(document).ready(function() {
            var body = $('body');
            var spinner = $('#spinner');

            body.css({opacity: '0.7'});

            var hideSpinner = function() {
                body.css({opacity: '1'});
                spinner.hide();
            };

            setTimeout(hideSpinner, 500);
        });
    </script>
</body>
</html>

templates/home/index.html
{% extends 'home/base.html' %}
{% block title %}{% endblock %}
{% block head %}
    <style>
        #homepage-card {
            min-height: 375px;
        }

        #upload-icon,
        #search-icon {
            font-size: 15rem;
            color: #007bff;
            opacity: 0.6;
        }

        #nav-cards-row {
            margin-bottom: 4rem;
        }

        #view-all-link {
            font-size: 1.25rem;
        }

        #view-all-link:hover {
            text-decoration: none;
            opacity: 0.7;
        }

        #view-all-icon {
            font-size: 1.1rem;
            margin-left: 0.5rem;
        }

        /* Carousel base class */
        .carousel {
            margin-bottom: 4rem;
        }

        /* Since positioning the image, we need to help out the caption */
        .carousel-caption {
            bottom: 3rem;
            z-index: 10;
        }

        /* Declare heights because of positioning of img element */
        .carousel-item {
            height: 28rem;
            background-color: #777;
        }

        .carousel-item > img {
            position: absolute;
            top: 0;
            left: 0;
            min-width: 100%;
            height: 32rem;
        }

        .marketing .col-lg-4 {
            margin-bottom: 1.5rem;
            text-align: center;
        }

        .marketing h2 {
            font-weight: 400;
        }

        .marketing .col-lg-4 p {
            margin-right: .75rem;
            margin-left: .75rem;
        }

        .featurette-divider {
            margin: 5rem 0; /* Space out the Bootstrap <hr> more */
        }

        .featurette-heading {
            font-weight: 300;
            line-height: 1;
            letter-spacing: -.05rem;
        }

        @media (min-width: 40em) {
            /* Bump up size of carousel content */
            .carousel-caption p {
                margin-bottom: 1.25rem;
                font-size: 1.25rem;
                line-height: 1.4;
            }

            .featurette-heading {
                font-size: 50px;
            }
        }

        @media (min-width: 62em) {
            .featurette-heading {
                margin-top: 7rem;
            }
        }
    </style>
{% endblock %}
{% block body %}
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="first-slide"
                     src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                     alt="First slide">
                <div class="container">
                    <div class="carousel-caption text-left">
                        <h1>School Made Easy</h1>
                        <p>Start using the number one homework sharing platform</p>
                        <div class="btn-group">
                            <p><a class="btn btn-lg btn-primary mr-4" href="/assignments/search/" role="button">Search</a></p>
                            <p><a class="btn btn-lg btn-primary" href="/upload/" role="button">Upload</a></p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="carousel-item">
                <img class="second-slide"
                     src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                     alt="Second slide">
                <div class="container">
                    <div class="carousel-caption text-left">
                        <h1>Search For Homework</h1>
                        <p>Find homework assignments by filter through your state and school</p>
                        <p><a class="btn btn-lg btn-primary" href="/assignments/search/" role="button">Search</a></p>
                    </div>
                </div>
            </div>

            <div class="carousel-item">
                <img class="third-slide"
                     src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                     alt="Third slide">
                <div class="container">
                    <div class="carousel-caption text-left">
                        <h1>Upload</h1>
                        <p>Contribute to our platform by uploading your own homework assignments</p>
                        <p><a class="btn btn-lg btn-primary" href="/upload/" role="button">Upload</a></p>
                    </div>
                </div>
            </div>

        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <!-- Cards Row -->
    <div id="nav-cards-row" class="row">
        <div class="col-md-6 col-sm-12 mb-4">
            <div id="homepage-card" class="card shadow pt-4 pb-2">
                <div align="center">
                    <i id="upload-icon" class="fas fa-upload card-img-top"></i>
                </div>
                <hr class="mt-4 mb-0">
                <div class="card-body">
                    <h5 class="card-title">Upload</h5>
                    <p>Contribute by uploading homework assignments</p>
                    <a href="/upload/" class="btn btn-outline-primary">Upload</a>
                </div>
            </div>
        </div>

        <div class="col-md-6 col-sm-12 mb-4">
            <div id="homepage-card" class="card shadow pt-4 pb-2">
                <div align="center">
                    <i id="search-icon" class="fas fa-search card-img-top"></i>
                </div>
                <hr class="mt-4 mb-0">
                <div class="card-body">
                    <h5 class="card-title">Search</h5>
                    <p>Search our platform to find homework assignments</p>
                    <a href="/assignments/search/" class="btn btn-outline-primary">Search</a>
                </div>
            </div>
        </div>
    </div>

    <h2 class="text-center">Latest Posted Assignments</h2>
    <div id="latest-assignments-row" class="row mt-4">
        {% for assignment in latest_assignments %}

            <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                <div class="card shadow">
                    <div class="card-header">
                        <h5 class="card-title">{{ assignment.title }}</h5>
                    </div>
                    <div class="card-body">
                        <p>{{ assignment.class_name }}</p>
                        <p class="float-left">{{ assignment.timestamp|date:"M d, Y" }}</p>
                        <p class="float-left ml-3">{{ assignment.school_name }}</p>
                        <p class="float-left ml-3">{{ assignment.state }}</p>
                        <div style="clear: both;"></div>
                        <a href="/assignments/view/{{ assignment.pk }}/" class="btn btn-primary">View Assignment</a>
                    </div>
                </div>
            </div>

        {% endfor %}
    </div>

    {% if latest_assignments.count > 0 %}
        <div align="center">
            <a href="/assignments/view/all/" id="view-all-link">
                View All<i id="view-all-icon" class="fas fa-chevron-right"></i>
            </a>
        </div>
    {% endif %}

{% endblock %}
{% block script %}

{% endblock %}

templates/home/upload.html
{% extends 'home/base.html' %}
{% block title %}{% endblock %}
{% block head %}
    <style>
        #main-container {
            margin-top: 40px;
            margin-bottom: 75px;
        }
        .invalid-feedback {
            display: none;
        }

    </style>
{% endblock %}
{% block body %}
<div id="main-container" class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
        <div class="card shadow px-4 py-2">
            <h4 class="card-title mt-2 mb-4">Upload an Assignment</h4>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.errors }}

                <div class="form-group">
                    <label for="id_email">Email</label>
                    {{ form.email }}
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="id_state">Select Your State</label>
                        {{ form.state }}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="id_school_name">School Name</label>
                        {{ form.school_name }}
                        <small class="form-text text-muted">
                            <span id="school-name-char">75</span> characters left
                        </small>
                        <div id="school-name-invalid-feedback" class="invalid-feedback">
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="id_title">Class Name</label>
                    {{ form.class_name }}
                </div>

                <div class="form-group">
                    <label for="id_title">Assignment Title</label>
                    {{ form.title }}
                    <small class="form-text text-muted">
                        <span id="title-char">150</span> characters left
                    </small>
                    <div id="title-invalid-feedback" class="invalid-feedback">
                    </div>
                </div>

                <div class="form-group">
                    <label for="id_title">Extra Notes</label>
                    {{ form.notes }}
                    <small class="form-text text-muted">
                        <span id="notes-char">2000</span> characters left
                    </small>
                    <div id="notes-invalid-feedback" class="invalid-feedback">
                    </div>
                </div>

                <p>You can add up to five pictures for an assignment, but only one is required</p>
                {{ formset.management_form }}
                {% for form in formset %}
                    <div class="form-group mt-4">
                    <div class="custom-file">
                        {{ form.image }}
                        <label class="custom-file-label" for="id_image">Choose file</label>
                    </div>
                </div>
                {% endfor %}

                <button type="submit" class="btn btn-outline-primary mt-2 mb-3">Upload</button>
            </form>
        </div>
    </div>
    <div class="col-md-2">

    </div>
</div>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function(){


            var schoolName = $('#id_school_name');
            var schoolNameChar = $('#school-name-char');
            var schoolInvalidText = $('#school-name-invalid-feedback');

            schoolName.keyup(function(){
                var currentChars = schoolName.val().length;
                var calcValue = 75 - currentChars;
                schoolNameChar.text(calcValue);
                if (calcValue < 0) {
                    schoolName.css('border', '1px solid red');
                    schoolInvalidText.text('School name cannot be more than 75 characters').show();
                } else {
                    schoolName.css('border', '1px solid #ced4da');
                    schoolInvalidText.hide();
                }
            });

            var title = $('#id_title');
            var titleChar = $('#title-char');
            var titleInvalidText = $('#title-invalid-feedback');

            title.keyup(function(){
                var currentChars = title.val().length;
                var calcValue = 150 - currentChars;
                titleChar.text(calcValue);
                if (calcValue < 0) {
                    title.css('border', '1px solid red');
                    titleInvalidText.text('Title cannot be more than 150 characters').show();
                } else {
                    title.css('border', '1px solid #ced4da');
                    titleInvalidText.hide();
                }
            });

            var notes = $('#id_notes');
            var notesChar = $('#notes-char');
            var notesInvalidText = $('#notes-invalid-feedback');

            notes.keyup(function(){
                var currentChars = notes.val().length;
                var calcValue = 2000 - currentChars;
                notesChar.text(calcValue);
                if (calcValue < 0) {
                    notes.css('border', '1px solid red');
                    notesInvalidText.text('Notes cannot be more than 2000 characters').show();
                } else {
                    notes.css('border', '1px solid #ced4da');
                    notesInvalidText.hide();
                }
            });

        });
    </script>
{% endblock %}